### PR TITLE
Upgrade to stylelint 15 & stylelint-order 6.0.2

### LINKED ISSUE #78: Stylelint 15 support
This works with stylelint 15 without issue, but there's a peer dependency warning. Simple to fix by updating to stylelint 15 in your package.json.

```
warning "stylelint-config-idiomatic-order > stylelint-order@5.0.0" has incorrect peer dependency "stylelint@^14.0.0".
```

### PR DESCRIPTION
**Pull request by rosiehsmith**
This would resolve https://github.com/ream88/stylelint-config-idiomatic-order/issues/78

### CODE REVIEW

**Comment by spacedawwwg** [comment]
It would be nice to get this one merged in

**Comment by spacedawwwg** [comment]
@ream88 just wondering if you'd be able to take a look at this PR?

**Comment by slashwhatever** [comment]
@ream88 any news on finding time to merge this please?

**Comment by ream88** [comment]
Maybe anyone can help with this: https://github.com/ream88/stylelint-config-idiomatic-order/discussions/81

**Comment by mvadari** [comment]
@ream88 any update?

**Comment by stevensacks** [comment]
@ream88 Can you please merge this in?

**Comment by mauriciabad** [comment]
Ping @ream88 Please merge the PR

**Pull request merged**
